### ISSUE TITLE
Remove possibility for characters to be assigned duplicate jobs

### ISSUE THREAD

**Issue by jressey** [ReverendUnk/FF12-IZJS-Job-and-Party-Randomizer#1]
It is possible for characters to get the same job as other characters.  Create protection for those scenarios.

**Comment by ReverendUnk** [comment]
Though I may expand the code in the future for various other settings such as no job duplication, the possibility of it happening was actually an intended feature. My bad for not stating as such anywhere.

**Comment by jressey** [comment]
I definitely want to respect your vision, but I'm still going to submit a pull request in case you want it in the future.  Are you at least open to allowing duplication to be optional?

**Comment by ReverendUnk** [comment]
Yep. And you're now a contributor as requested. =)

**Comment by ReverendUnk** [comment]
If you hadn't already noticed, I've merged your pull request with the main branch, as I feel that job duplication - while originally an intended feature - is, on the whole, an undesired feature by the main user-base.
