### ISSUE TITLE
Try again button doesn't work

### ISSUE THREAD

**Issue by jressey** [ReverendUnk/FF12-IZJS-Job-and-Party-Randomizer#2]

**Comment by ReverendUnk** [comment]
Works fine in Chrome. Which means it's an IE or Firefox issue. I'll try and pin down a fix as I can.

**Comment by ReverendUnk** [comment]
Dev consoles on both Firefox and IE claim that the run() in the try again button isn't defined. Still poking at a possible fix, but no luck as of yet.

**Comment by ReverendUnk** [comment]
Issue believed to be fixed via workaround in Firefox. IE still misbehaving.

**Comment by ReverendUnk** [comment]
Closing this issue as the code now fully works in Firefox, and the IE issue has escalated beyond the original scope of this issue.
